#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import subprocess

request = json.load(sys.stdin)
user = request['user']
groups = request.get('groups', [])
password = request.get('password', '') # Empty string implies a random password is set
display_name = request.get('display_name', '')

adduser_cmd = ['podman', 'exec', '-i', 'openldap', 'add-user']

if groups:
    adduser_cmd += ['-g', ','.join(groups)]

if password:
    adduser_cmd += ['-p', '-'] # Read password from stdin
else:
    password=None
    adduser_cmd += ['-p', ''] # Generate a random password

if display_name:
    adduser_cmd += ['-d', display_name]

adduser_cmd.append(user)

subprocess.run(adduser_cmd, input=password, stdout=sys.stderr, check=True, text=True)
