#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import agent
import json
import cluster.userdomains

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

request = json.load(sys.stdin)

domain = request['domain'].lower()
provision = request['provision']

with agent.redis_connect() as rdb:
    domains = cluster.userdomains.get_internal_domains(rdb) | cluster.userdomains.get_external_domains(rdb)

if domain in domains and provision == 'new-domain':
    agent.set_status('validation-failed')
    json.dump([{'field':'domain', 'parameter':'domain','value': domain, 'error':'domain_already_exists'}], fp=sys.stdout)
    sys.exit(2)

if not domain in domains and provision == 'join-domain':
    agent.set_status('validation-failed')
    json.dump([{'field':'domain', 'parameter':'domain','value': domain, 'error':'domain_not_found'}], fp=sys.stdout)
    sys.exit(3)
