#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import subprocess

request = json.load(sys.stdin)
user = request['user']

alteruser_cmd = ['podman', 'exec', '-i', 'openldap', 'alter-user']

if 'password' in request:
    alteruser_cmd += ['-p', '-'] # Write password to helper's stdin

if 'groups' in request:
    alteruser_cmd += ['-g', ','.join(request['groups'])]

if 'full_name' in request:
    alteruser_cmd += ['-f', request['full_name']]

alteruser_cmd.append(user)

subprocess.run(alteruser_cmd, input=request.get('password'), stdout=sys.stderr, check=True, text=True)
