#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os
import cluster.userdomains

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

request = json.load(sys.stdin)
original_environment = request['environment']
domain = original_environment['LDAP_DOMAIN']

rdb = agent.redis_connect(host='127.0.0.1')

domains = cluster.userdomains.list_domains(rdb)
if domain in domains:
    # This is a disaster recovery: the domain must not exist!
    agent.set_status('validation-failed')
    json.dump([{'field':'environment', 'parameter':'environment','value': domain, 'error':'domain_already_exists'}], fp=sys.stdout)
    sys.exit(2)
