#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2
set -e

echo "Resume OpenLDAP server state:"
podman run \
    --env=LDAP_\* \
    --log-driver=none \
    --replace --name=load_dumpfiles --rm \
    --volume=data:/var/lib/openldap:Z \
    --network=host \
    "${OPENLDAP_SERVER_IMAGE}" /usr/local/bin/load-dumpfiles

